--------------------------------------------------------
-- Archivo creado  - martes-noviembre-18-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GEN_ESTADO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."GEN_ESTADO" 
   (	"id_estado" NUMBER, 
	"nombre" VARCHAR2(50 BYTE), 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table GEN_PERIODO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."GEN_PERIODO" 
   (	"id_periodo" NUMBER, 
	"per_id_periodo" NUMBER, 
	"mes" VARCHAR2(50 BYTE), 
	"descripcion" VARCHAR2(50 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table GEN_SOLICITUD_FINACIERA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."GEN_SOLICITUD_FINACIERA" 
   (	"id_solicitud" NUMBER, 
	"codigo" NUMBER, 
	"id_fuente_financiamiento" NUMBER, 
	"id_tipo_solicitud" NUMBER, 
	"id_periodo" NUMBER, 
	"id_meta" NUMBER, 
	"monto" NUMBER(8,2), 
	"descripcion" VARCHAR2(100 BYTE), 
	"fecha_realizacion" DATE, 
	"fecha_pago" DATE, 
	"id_estado" NUMBER, 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table GEN_TIPO_SOLICITUD
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."GEN_TIPO_SOLICITUD" 
   (	"id_tipo_solicitud" NUMBER, 
	"nombre" VARCHAR2(50 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table GEN_UNIDAD_MEDIDA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."GEN_UNIDAD_MEDIDA" 
   (	"id_unidad_medida" NUMBER, 
	"descripcion" VARCHAR2(50 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table KATUN_EJE
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."KATUN_EJE" 
   (	"id_katun_eje" NUMBER, 
	"id_katun_prioridad" NUMBER, 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table KATUN_META
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."KATUN_META" 
   (	"id_katun_meta" NUMBER, 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table KATUN_PRIORIDAD
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."KATUN_PRIORIDAD" 
   (	"id_katun_prioridad" NUMBER, 
	"id_katun_meta" NUMBER, 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table POA_META
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."POA_META" 
   (	"id_meta" NUMBER, 
	"id_sub_producto" NUMBER, 
	"id_unidad_medida" NUMBER, 
	"descripcion" VARCHAR2(100 BYTE), 
	"resultado_esperado" NUMBER, 
	"id_katun_meta" NUMBER, 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table POA_META_DIRECCION
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."POA_META_DIRECCION" 
   (	"id_meta" NUMBER, 
	"id_unidad" NUMBER, 
	"observaciones" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table POA_META_PERIODO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."POA_META_PERIODO" 
   (	"id_periodo" NUMBER, 
	"id_meta" NUMBER, 
	"resultado_programado" NUMBER, 
	"resultado_ejecutado" NUMBER, 
	"observaciones" VARCHAR2(1024 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table POA_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."POA_PRODUCTO" 
   (	"id_producto" NUMBER, 
	"descripcion" VARCHAR2(100 BYTE), 
	"inciso" NUMBER, 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table POA_SUB_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."POA_SUB_PRODUCTO" 
   (	"id_sub_producto" NUMBER, 
	"id_producto" NUMBER, 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table PRUEBA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."PRUEBA" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table RRHH_CAPACITACION_PUESTO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."RRHH_CAPACITACION_PUESTO" 
   (	"id_detalle_capacitacion" NUMBER, 
	"id_tipo_puesto" NUMBER, 
	"descripcion" VARCHAR2(50 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table RRHH_CARACTER_CAPACITACION
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."RRHH_CARACTER_CAPACITACION" 
   (	"id_caracter" NUMBER, 
	"nombre" VARCHAR2(25 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table RRHH_DETALLE_CAPACITACION
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."RRHH_DETALLE_CAPACITACION" 
   (	"id_detalle" NUMBER, 
	"id_solicitud_capacitacion" NUMBER, 
	"problematica" VARCHAR2(100 BYTE), 
	"tema" VARCHAR2(100 BYTE), 
	"prioridad" CHAR(1 BYTE), 
	"nivel_economico" CHAR(1 BYTE), 
	"duracion" NUMBER(2,2), 
	"id_caracter" VARCHAR2(20 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table RRHH_PERSONA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."RRHH_PERSONA" 
   (	"id_persona" NUMBER, 
	"nombres" VARCHAR2(100 BYTE), 
	"apellidos" VARCHAR2(100 BYTE), 
	"direccion" VARCHAR2(100 BYTE), 
	"telefono" NUMBER(10,0), 
	"correo_electronico" VARCHAR2(100 BYTE), 
	"id_tipo_puesto" NUMBER, 
	"id_encargado" NUMBER, 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table RRHH_SOLICITUD_CAPACITACION
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" 
   (	"id_solicitud_capacitacion" NUMBER, 
	"correlativo" VARCHAR2(20 BYTE), 
	"id_unidad_administrativa" NUMBER, 
	"total_personal" NUMBER, 
	"usr_crea" NUMBER, 
	"id_meta" NUMBER, 
	"id_estado" NUMBER, 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table RRHH_TIPO_PUESTO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."RRHH_TIPO_PUESTO" 
   (	"id_tipo_puesto" NUMBER, 
	"nombre" VARCHAR2(50 BYTE), 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table RRHH_UNIDAD_ADMINISTRATIVA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."RRHH_UNIDAD_ADMINISTRATIVA" 
   (	"id_unidad_admin" NUMBER(*,0), 
	"id_subordinado" NUMBER(38,0), 
	"nombre" VARCHAR2(100 BYTE), 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_BITACORA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_BITACORA" 
   (	"id_bitacora" NUMBER, 
	"id_sesion" NUMBER, 
	"fecha_crea" DATE, 
	"fecha_mod" DATE, 
	"operacion" VARCHAR2(100 BYTE), 
	"id_pagina" NUMBER, 
	"tablas" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_MODULO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_MODULO" 
   (	"id_modulo" NUMBER(*,0), 
	"nombre" VARCHAR2(50 BYTE), 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_PAGINA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_PAGINA" 
   (	"id_pagina" NUMBER(*,0), 
	"nombre" VARCHAR2(50 BYTE), 
	"url" VARCHAR2(100 BYTE), 
	"descripcion" VARCHAR2(100 BYTE), 
	"id_modulo" NUMBER(38,0), 
	"restrictiva" CHAR(1 BYTE), 
	"id_tipo_pagina" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_PAGINA_ASIGNADA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_PAGINA_ASIGNADA" 
   (	"id_asignacion" NUMBER, 
	"id_pagina" NUMBER(*,0), 
	"id_rol" NUMBER(*,0), 
	"id_usuario" NUMBER(*,0), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_PRIVILEGIO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_PRIVILEGIO" 
   (	"id_privilegio" NUMBER(*,0), 
	"nombre" VARCHAR2(50 BYTE), 
	"descripcion" VARCHAR2(100 BYTE), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_PRIVILEGIO_PAGINA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_PRIVILEGIO_PAGINA" 
   (	"id_privilegio" NUMBER(*,0), 
	"id_asignacion_pagina" NUMBER(*,0), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_ROL
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_ROL" 
   (	"id_rol" NUMBER(*,0), 
	"nombre" VARCHAR2(50 BYTE), 
	"descripcion" VARCHAR2(100 BYTE), 
	"id_unidad_admin" NUMBER(38,0), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_ROL_USUARIO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_ROL_USUARIO" 
   (	"id_rol" NUMBER(*,0), 
	"id_usuario" NUMBER(*,0), 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_SESION
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_SESION" 
   (	"id_sesion" NUMBER, 
	"id_usuario" NUMBER, 
	"hora_inicio" DATE, 
	"hora_fin" DATE, 
	"fecha_sesion" DATE, 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_TIPO_PAGINA
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_TIPO_PAGINA" 
   (	"id_tipo_pagina" NUMBER, 
	"nombre" VARCHAR2(50 BYTE), 
	"descripcion" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Table SEG_USUARIO
--------------------------------------------------------

  CREATE TABLE "SCHE$SISAG"."SEG_USUARIO" 
   (	"id_usuario" NUMBER(38,0), 
	"nombre" VARCHAR2(50 BYTE), 
	"pwd" VARCHAR2(100 BYTE), 
	"pregunta" VARCHAR2(100 BYTE), 
	"respuesta" VARCHAR2(100 BYTE), 
	"estado" CHAR(1 BYTE), 
	"email" VARCHAR2(100 BYTE), 
	"telefono" NUMBER(10,0), 
	"id_persona" NUMBER, 
	"restrictiva" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
REM INSERTING into SCHE$SISAG.GEN_ESTADO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.GEN_PERIODO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.GEN_SOLICITUD_FINACIERA
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.GEN_TIPO_SOLICITUD
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.GEN_UNIDAD_MEDIDA
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.KATUN_EJE
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.KATUN_META
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.KATUN_PRIORIDAD
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.POA_META
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.POA_META_DIRECCION
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.POA_META_PERIODO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.POA_PRODUCTO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.POA_SUB_PRODUCTO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.PRUEBA
SET DEFINE OFF;
Insert into SCHE$SISAG.PRUEBA (ID,NOMBRE) values (1,'sadfasdf');
REM INSERTING into SCHE$SISAG.RRHH_CAPACITACION_PUESTO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.RRHH_CARACTER_CAPACITACION
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.RRHH_DETALLE_CAPACITACION
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.RRHH_PERSONA
SET DEFINE OFF;
Insert into SCHE$SISAG.RRHH_PERSONA ("id_persona","nombres","apellidos","direccion","telefono","correo_electronico","id_tipo_puesto","id_encargado","restrictiva") values (1,'super','admin','Guatemala',55555555,null,1,null,null);
REM INSERTING into SCHE$SISAG.RRHH_SOLICITUD_CAPACITACION
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.RRHH_TIPO_PUESTO
SET DEFINE OFF;
Insert into SCHE$SISAG.RRHH_TIPO_PUESTO ("id_tipo_puesto","nombre","descripcion","restrictiva") values (1,'INFORMATICA','Pertenece a Direccion Informatica',null);
REM INSERTING into SCHE$SISAG.RRHH_UNIDAD_ADMINISTRATIVA
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_BITACORA
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_MODULO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_PAGINA
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_PAGINA_ASIGNADA
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_PRIVILEGIO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_PRIVILEGIO_PAGINA
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_ROL
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_ROL_USUARIO
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_SESION
SET DEFINE OFF;
REM INSERTING into SCHE$SISAG.SEG_TIPO_PAGINA
SET DEFINE OFF;
Insert into SCHE$SISAG.SEG_TIPO_PAGINA ("id_tipo_pagina","nombre","descripcion") values (1,'principal','Tipo de pagina publica no necesita ser asignada');
REM INSERTING into SCHE$SISAG.SEG_USUARIO
SET DEFINE OFF;
Insert into SCHE$SISAG.SEG_USUARIO ("id_usuario","nombre","pwd","pregunta","respuesta","estado","email","telefono","id_persona","restrictiva") values (1,'ADMIN','73acd9a5972130b75066c82595a1fae3',null,null,'1',null,null,1,null);
--------------------------------------------------------
--  DDL for Index GEN_ESTADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."GEN_ESTADO_PK" ON "SCHE$SISAG"."GEN_ESTADO" ("id_estado") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index PERIODO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."PERIODO_PK" ON "SCHE$SISAG"."GEN_PERIODO" ("id_periodo") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index SOLICITUD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."SOLICITUD_PK" ON "SCHE$SISAG"."GEN_SOLICITUD_FINACIERA" ("id_solicitud") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index TIPO_SOLICITUD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."TIPO_SOLICITUD_PK" ON "SCHE$SISAG"."GEN_TIPO_SOLICITUD" ("id_tipo_solicitud") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index UNIDAD_MEDIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."UNIDAD_MEDIDA_PK" ON "SCHE$SISAG"."GEN_UNIDAD_MEDIDA" ("id_unidad_medida") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index KATUN_EJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."KATUN_EJE_PK" ON "SCHE$SISAG"."KATUN_EJE" ("id_katun_eje") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index KATUN_META_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."KATUN_META_PK" ON "SCHE$SISAG"."KATUN_META" ("id_katun_meta") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index KATUN_PRIORIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."KATUN_PRIORIDAD_PK" ON "SCHE$SISAG"."KATUN_PRIORIDAD" ("id_katun_prioridad") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index META_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."META_PK" ON "SCHE$SISAG"."POA_META" ("id_meta") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index META_DIRECCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."META_DIRECCION_PK" ON "SCHE$SISAG"."POA_META_DIRECCION" ("id_meta", "id_unidad") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index META_PERIODO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."META_PERIODO_PK" ON "SCHE$SISAG"."POA_META_PERIODO" ("id_periodo", "id_meta") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."PRODUCTO_PK" ON "SCHE$SISAG"."POA_PRODUCTO" ("id_producto") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index SUB_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."SUB_PRODUCTO_PK" ON "SCHE$SISAG"."POA_SUB_PRODUCTO" ("id_sub_producto") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index SYS_C0084014
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."SYS_C0084014" ON "SCHE$SISAG"."PRUEBA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index ASIGNA_CAPACITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."ASIGNA_CAPACITACION_PK" ON "SCHE$SISAG"."RRHH_CAPACITACION_PUESTO" ("id_detalle_capacitacion", "id_tipo_puesto") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index GEN_CARACTER_CAPACITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."GEN_CARACTER_CAPACITACION_PK" ON "SCHE$SISAG"."RRHH_CARACTER_CAPACITACION" ("id_caracter") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index GEN_DETALLE_CAPACITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."GEN_DETALLE_CAPACITACION_PK" ON "SCHE$SISAG"."RRHH_DETALLE_CAPACITACION" ("id_detalle") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index SEG_PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."SEG_PERSONA_PK" ON "SCHE$SISAG"."RRHH_PERSONA" ("id_persona") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index GEN_SOLICITUD_CAPACITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."GEN_SOLICITUD_CAPACITACION_PK" ON "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" ("id_solicitud_capacitacion") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index SEG_TIPO_PUESTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."SEG_TIPO_PUESTO_PK" ON "SCHE$SISAG"."RRHH_TIPO_PUESTO" ("id_tipo_puesto") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index UNIDAD_ADMINISTRATIVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."UNIDAD_ADMINISTRATIVA_PK" ON "SCHE$SISAG"."RRHH_UNIDAD_ADMINISTRATIVA" ("id_unidad_admin") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index BITACORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."BITACORA_PK" ON "SCHE$SISAG"."SEG_BITACORA" ("id_bitacora") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index MODULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."MODULO_PK" ON "SCHE$SISAG"."SEG_MODULO" ("id_modulo") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index PAGINA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."PAGINA_PK" ON "SCHE$SISAG"."SEG_PAGINA" ("id_pagina") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index PAGINA_ASIGNADA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."PAGINA_ASIGNADA_PK" ON "SCHE$SISAG"."SEG_PAGINA_ASIGNADA" ("id_asignacion") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index PRIVILEGIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."PRIVILEGIO_PK" ON "SCHE$SISAG"."SEG_PRIVILEGIO" ("id_privilegio") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index PRIVILEGIO_PAGINA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."PRIVILEGIO_PAGINA_PK" ON "SCHE$SISAG"."SEG_PRIVILEGIO_PAGINA" ("id_privilegio", "id_asignacion_pagina") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."ROL_PK" ON "SCHE$SISAG"."SEG_ROL" ("id_rol") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index ROL_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."ROL_USUARIO_PK" ON "SCHE$SISAG"."SEG_ROL_USUARIO" ("id_usuario", "id_rol") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index SESION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."SESION_PK" ON "SCHE$SISAG"."SEG_SESION" ("id_sesion") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index SEG_TIPO_PAGINA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."SEG_TIPO_PAGINA_PK" ON "SCHE$SISAG"."SEG_TIPO_PAGINA" ("id_tipo_pagina") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHE$SISAG"."USUARIO_PK" ON "SCHE$SISAG"."SEG_USUARIO" ("id_usuario") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG" ;
--------------------------------------------------------
--  Constraints for Table GEN_ESTADO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."GEN_ESTADO" ADD CONSTRAINT "GEN_ESTADO_PK" PRIMARY KEY ("id_estado")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."GEN_ESTADO" MODIFY ("id_estado" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GEN_PERIODO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."GEN_PERIODO" ADD CONSTRAINT "PERIODO_PK" PRIMARY KEY ("id_periodo")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."GEN_PERIODO" MODIFY ("id_periodo" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GEN_SOLICITUD_FINACIERA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."GEN_SOLICITUD_FINACIERA" ADD CONSTRAINT "SOLICITUD_PK" PRIMARY KEY ("id_solicitud")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."GEN_SOLICITUD_FINACIERA" MODIFY ("id_solicitud" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GEN_TIPO_SOLICITUD
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."GEN_TIPO_SOLICITUD" MODIFY ("id_tipo_solicitud" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."GEN_TIPO_SOLICITUD" ADD CONSTRAINT "TIPO_SOLICITUD_PK" PRIMARY KEY ("id_tipo_solicitud")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GEN_UNIDAD_MEDIDA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."GEN_UNIDAD_MEDIDA" MODIFY ("id_unidad_medida" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."GEN_UNIDAD_MEDIDA" ADD CONSTRAINT "UNIDAD_MEDIDA_PK" PRIMARY KEY ("id_unidad_medida")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KATUN_EJE
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."KATUN_EJE" ADD CONSTRAINT "KATUN_EJE_PK" PRIMARY KEY ("id_katun_eje")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."KATUN_EJE" MODIFY ("id_katun_eje" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KATUN_META
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."KATUN_META" ADD CONSTRAINT "KATUN_META_PK" PRIMARY KEY ("id_katun_meta")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."KATUN_META" MODIFY ("id_katun_meta" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KATUN_PRIORIDAD
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."KATUN_PRIORIDAD" ADD CONSTRAINT "KATUN_PRIORIDAD_PK" PRIMARY KEY ("id_katun_prioridad")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."KATUN_PRIORIDAD" MODIFY ("id_katun_prioridad" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POA_META
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_META" ADD CONSTRAINT "META_PK" PRIMARY KEY ("id_meta")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_META" MODIFY ("id_meta" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POA_META_DIRECCION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_META_DIRECCION" ADD CONSTRAINT "META_DIRECCION_PK" PRIMARY KEY ("id_meta", "id_unidad")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_META_DIRECCION" MODIFY ("id_meta" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."POA_META_DIRECCION" MODIFY ("id_unidad" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POA_META_PERIODO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_META_PERIODO" ADD CONSTRAINT "META_PERIODO_PK" PRIMARY KEY ("id_periodo", "id_meta")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_META_PERIODO" MODIFY ("id_periodo" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."POA_META_PERIODO" MODIFY ("id_meta" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POA_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("id_producto")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_PRODUCTO" MODIFY ("id_producto" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POA_SUB_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_SUB_PRODUCTO" ADD CONSTRAINT "SUB_PRODUCTO_PK" PRIMARY KEY ("id_sub_producto")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_SUB_PRODUCTO" MODIFY ("id_sub_producto" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRUEBA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."PRUEBA" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."PRUEBA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RRHH_CAPACITACION_PUESTO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_CAPACITACION_PUESTO" ADD CONSTRAINT "ASIGNA_CAPACITACION_PK" PRIMARY KEY ("id_detalle_capacitacion", "id_tipo_puesto")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_CAPACITACION_PUESTO" MODIFY ("id_detalle_capacitacion" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."RRHH_CAPACITACION_PUESTO" MODIFY ("id_tipo_puesto" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RRHH_CARACTER_CAPACITACION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_CARACTER_CAPACITACION" ADD CONSTRAINT "GEN_CARACTER_CAPACITACION_PK" PRIMARY KEY ("id_caracter")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_CARACTER_CAPACITACION" MODIFY ("id_caracter" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RRHH_DETALLE_CAPACITACION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_DETALLE_CAPACITACION" ADD CONSTRAINT "GEN_DETALLE_CAPACITACION_PK" PRIMARY KEY ("id_detalle")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_DETALLE_CAPACITACION" MODIFY ("id_detalle" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RRHH_PERSONA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_PERSONA" ADD CONSTRAINT "SEG_PERSONA_PK" PRIMARY KEY ("id_persona")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_PERSONA" MODIFY ("id_persona" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RRHH_SOLICITUD_CAPACITACION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" ADD CONSTRAINT "GEN_SOLICITUD_CAPACITACION_PK" PRIMARY KEY ("id_solicitud_capacitacion")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" MODIFY ("id_solicitud_capacitacion" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RRHH_TIPO_PUESTO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_TIPO_PUESTO" ADD CONSTRAINT "SEG_TIPO_PUESTO_PK" PRIMARY KEY ("id_tipo_puesto")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_TIPO_PUESTO" MODIFY ("id_tipo_puesto" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RRHH_UNIDAD_ADMINISTRATIVA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_UNIDAD_ADMINISTRATIVA" MODIFY ("id_unidad_admin" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."RRHH_UNIDAD_ADMINISTRATIVA" ADD CONSTRAINT "UNIDAD_ADMINISTRATIVA_PK" PRIMARY KEY ("id_unidad_admin")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEG_BITACORA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_BITACORA" ADD CONSTRAINT "BITACORA_PK" PRIMARY KEY ("id_bitacora")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_BITACORA" MODIFY ("id_bitacora" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_MODULO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_MODULO" ADD CONSTRAINT "MODULO_PK" PRIMARY KEY ("id_modulo")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_MODULO" MODIFY ("id_modulo" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_PAGINA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA" ADD CONSTRAINT "PAGINA_PK" PRIMARY KEY ("id_pagina")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA" MODIFY ("id_pagina" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_PAGINA_ASIGNADA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA_ASIGNADA" ADD CONSTRAINT "PAGINA_ASIGNADA_PK" PRIMARY KEY ("id_asignacion")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA_ASIGNADA" MODIFY ("id_asignacion" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_PRIVILEGIO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_PRIVILEGIO" ADD CONSTRAINT "PRIVILEGIO_PK" PRIMARY KEY ("id_privilegio")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_PRIVILEGIO" MODIFY ("id_privilegio" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_PRIVILEGIO_PAGINA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_PRIVILEGIO_PAGINA" ADD CONSTRAINT "PRIVILEGIO_PAGINA_PK" PRIMARY KEY ("id_privilegio", "id_asignacion_pagina")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_PRIVILEGIO_PAGINA" MODIFY ("id_privilegio" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."SEG_PRIVILEGIO_PAGINA" MODIFY ("id_asignacion_pagina" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_ROL
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("id_rol")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_ROL" MODIFY ("id_rol" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_ROL_USUARIO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_ROL_USUARIO" ADD CONSTRAINT "ROL_USUARIO_PK" PRIMARY KEY ("id_usuario", "id_rol")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_ROL_USUARIO" MODIFY ("id_rol" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."SEG_ROL_USUARIO" MODIFY ("id_usuario" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_SESION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_SESION" ADD CONSTRAINT "SESION_PK" PRIMARY KEY ("id_sesion")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_SESION" MODIFY ("id_sesion" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_TIPO_PAGINA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_TIPO_PAGINA" ADD CONSTRAINT "SEG_TIPO_PAGINA_PK" PRIMARY KEY ("id_tipo_pagina")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_TIPO_PAGINA" MODIFY ("id_tipo_pagina" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEG_USUARIO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_USUARIO" MODIFY ("id_usuario" NOT NULL ENABLE);
 
  ALTER TABLE "SCHE$SISAG"."SEG_USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("id_usuario")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SCHE_SISAG"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GEN_PERIODO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."GEN_PERIODO" ADD CONSTRAINT "PERIODO_PERIODO_FK" FOREIGN KEY ("per_id_periodo")
	  REFERENCES "SCHE$SISAG"."GEN_PERIODO" ("id_periodo") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GEN_SOLICITUD_FINACIERA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."GEN_SOLICITUD_FINACIERA" ADD CONSTRAINT "GEN_SOLICITUD_FINACIERA_FK1" FOREIGN KEY ("id_estado")
	  REFERENCES "SCHE$SISAG"."GEN_ESTADO" ("id_estado") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."GEN_SOLICITUD_FINACIERA" ADD CONSTRAINT "SOLICITUD_META_FK" FOREIGN KEY ("id_meta")
	  REFERENCES "SCHE$SISAG"."POA_META" ("id_meta") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."GEN_SOLICITUD_FINACIERA" ADD CONSTRAINT "SOLICITUD_PERIODO_FK" FOREIGN KEY ("id_periodo")
	  REFERENCES "SCHE$SISAG"."GEN_PERIODO" ("id_periodo") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."GEN_SOLICITUD_FINACIERA" ADD CONSTRAINT "SOLICITUD_TIPO_SOLICITUD_FK" FOREIGN KEY ("id_tipo_solicitud")
	  REFERENCES "SCHE$SISAG"."GEN_TIPO_SOLICITUD" ("id_tipo_solicitud") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KATUN_EJE
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."KATUN_EJE" ADD CONSTRAINT "KATUN_EJE_PRIORIDAD_FK" FOREIGN KEY ("id_katun_prioridad")
	  REFERENCES "SCHE$SISAG"."KATUN_PRIORIDAD" ("id_katun_prioridad") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KATUN_PRIORIDAD
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."KATUN_PRIORIDAD" ADD CONSTRAINT "KATUN_PRIORIDAD_META_FK" FOREIGN KEY ("id_katun_meta")
	  REFERENCES "SCHE$SISAG"."KATUN_META" ("id_katun_meta") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POA_META
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_META" ADD CONSTRAINT "META_KATUN_META_FK" FOREIGN KEY ("id_katun_meta")
	  REFERENCES "SCHE$SISAG"."KATUN_META" ("id_katun_meta") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_META" ADD CONSTRAINT "META_SUB_PRODUCTO_FK" FOREIGN KEY ("id_sub_producto")
	  REFERENCES "SCHE$SISAG"."POA_SUB_PRODUCTO" ("id_sub_producto") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_META" ADD CONSTRAINT "META_UNIDAD_MEDIDA_FK" FOREIGN KEY ("id_unidad_medida")
	  REFERENCES "SCHE$SISAG"."GEN_UNIDAD_MEDIDA" ("id_unidad_medida") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POA_META_DIRECCION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_META_DIRECCION" ADD CONSTRAINT "META_DIRECCION_META_FK" FOREIGN KEY ("id_meta")
	  REFERENCES "SCHE$SISAG"."POA_META" ("id_meta") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_META_DIRECCION" ADD CONSTRAINT "META_DIRECCION_UNIDAD_FK" FOREIGN KEY ("id_unidad")
	  REFERENCES "SCHE$SISAG"."RRHH_UNIDAD_ADMINISTRATIVA" ("id_unidad_admin") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POA_META_PERIODO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_META_PERIODO" ADD CONSTRAINT "META_PERIODO_META_FK" FOREIGN KEY ("id_meta")
	  REFERENCES "SCHE$SISAG"."POA_META" ("id_meta") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."POA_META_PERIODO" ADD CONSTRAINT "META_PERIODO_PERIODO_FK" FOREIGN KEY ("id_periodo")
	  REFERENCES "SCHE$SISAG"."GEN_PERIODO" ("id_periodo") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POA_SUB_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."POA_SUB_PRODUCTO" ADD CONSTRAINT "SUB_PRODUCTO_PRODUCTO_FK" FOREIGN KEY ("id_producto")
	  REFERENCES "SCHE$SISAG"."POA_PRODUCTO" ("id_producto") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RRHH_CAPACITACION_PUESTO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_CAPACITACION_PUESTO" ADD CONSTRAINT "GEN_ASIGNA_CAPACITACION_FK1" FOREIGN KEY ("id_detalle_capacitacion")
	  REFERENCES "SCHE$SISAG"."RRHH_DETALLE_CAPACITACION" ("id_detalle") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_CAPACITACION_PUESTO" ADD CONSTRAINT "GEN_ASIGNA_CAPACITACION_FK2" FOREIGN KEY ("id_tipo_puesto")
	  REFERENCES "SCHE$SISAG"."RRHH_TIPO_PUESTO" ("id_tipo_puesto") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RRHH_DETALLE_CAPACITACION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_DETALLE_CAPACITACION" ADD CONSTRAINT "GEN_DETALLE_CAPACITACION_FK1" FOREIGN KEY ("id_solicitud_capacitacion")
	  REFERENCES "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" ("id_solicitud_capacitacion") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_DETALLE_CAPACITACION" ADD CONSTRAINT "GEN_DETALLE_CAPACITACION_FK2" FOREIGN KEY ("id_detalle")
	  REFERENCES "SCHE$SISAG"."RRHH_CARACTER_CAPACITACION" ("id_caracter") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RRHH_PERSONA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_PERSONA" ADD CONSTRAINT "SEG_PERSONA_FK1" FOREIGN KEY ("id_encargado")
	  REFERENCES "SCHE$SISAG"."RRHH_PERSONA" ("id_persona") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_PERSONA" ADD CONSTRAINT "SEG_PERSONA_FK2" FOREIGN KEY ("id_tipo_puesto")
	  REFERENCES "SCHE$SISAG"."RRHH_TIPO_PUESTO" ("id_tipo_puesto") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RRHH_SOLICITUD_CAPACITACION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" ADD CONSTRAINT "GEN_SOLICITUD_CAPACITACIO_FK1" FOREIGN KEY ("id_unidad_administrativa")
	  REFERENCES "SCHE$SISAG"."RRHH_UNIDAD_ADMINISTRATIVA" ("id_unidad_admin") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" ADD CONSTRAINT "GEN_SOLICITUD_CAPACITACIO_FK2" FOREIGN KEY ("usr_crea")
	  REFERENCES "SCHE$SISAG"."SEG_USUARIO" ("id_usuario") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" ADD CONSTRAINT "GEN_SOLICITUD_CAPACITACIO_FK3" FOREIGN KEY ("id_meta")
	  REFERENCES "SCHE$SISAG"."POA_META" ("id_meta") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."RRHH_SOLICITUD_CAPACITACION" ADD CONSTRAINT "GEN_SOLICITUD_CAPACITACIO_FK4" FOREIGN KEY ("id_estado")
	  REFERENCES "SCHE$SISAG"."GEN_ESTADO" ("id_estado") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEG_BITACORA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_BITACORA" ADD CONSTRAINT "BITACORA_PAGINA_FK" FOREIGN KEY ("id_pagina")
	  REFERENCES "SCHE$SISAG"."SEG_PAGINA" ("id_pagina") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_BITACORA" ADD CONSTRAINT "BITACORA_SESION_FK" FOREIGN KEY ("id_sesion")
	  REFERENCES "SCHE$SISAG"."SEG_SESION" ("id_sesion") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEG_PAGINA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA" ADD CONSTRAINT "PAGINA_MODULO_FK" FOREIGN KEY ("id_modulo")
	  REFERENCES "SCHE$SISAG"."SEG_MODULO" ("id_modulo") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA" ADD CONSTRAINT "SEG_PAGINA_FK1" FOREIGN KEY ("id_tipo_pagina")
	  REFERENCES "SCHE$SISAG"."SEG_TIPO_PAGINA" ("id_tipo_pagina") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEG_PAGINA_ASIGNADA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA_ASIGNADA" ADD CONSTRAINT "PAGINA_ASIGNADA_PAGINA_FK" FOREIGN KEY ("id_pagina")
	  REFERENCES "SCHE$SISAG"."SEG_PAGINA" ("id_pagina") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA_ASIGNADA" ADD CONSTRAINT "PAGINA_ASIGNADA_ROL_FK" FOREIGN KEY ("id_rol")
	  REFERENCES "SCHE$SISAG"."SEG_ROL" ("id_rol") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_PAGINA_ASIGNADA" ADD CONSTRAINT "PAGINA_ASIGNADA_USUARIO_FK" FOREIGN KEY ("id_usuario")
	  REFERENCES "SCHE$SISAG"."SEG_USUARIO" ("id_usuario") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEG_PRIVILEGIO_PAGINA
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_PRIVILEGIO_PAGINA" ADD CONSTRAINT "SEG_PRIVILEGIO_PAGINA_FK1" FOREIGN KEY ("id_asignacion_pagina")
	  REFERENCES "SCHE$SISAG"."SEG_PAGINA_ASIGNADA" ("id_asignacion") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_PRIVILEGIO_PAGINA" ADD CONSTRAINT "SEG_PRIVILEGIO_PAGINA_FK2" FOREIGN KEY ("id_privilegio")
	  REFERENCES "SCHE$SISAG"."SEG_PRIVILEGIO" ("id_privilegio") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEG_ROL
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_ROL" ADD CONSTRAINT "ROL_UNIDAD_ADMINISTRATIVA_FK" FOREIGN KEY ("id_unidad_admin")
	  REFERENCES "SCHE$SISAG"."RRHH_UNIDAD_ADMINISTRATIVA" ("id_unidad_admin") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEG_ROL_USUARIO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_ROL_USUARIO" ADD CONSTRAINT "ROL_USUARIO_ROL_FK" FOREIGN KEY ("id_rol")
	  REFERENCES "SCHE$SISAG"."SEG_ROL" ("id_rol") ENABLE;
 
  ALTER TABLE "SCHE$SISAG"."SEG_ROL_USUARIO" ADD CONSTRAINT "ROL_USUARIO_USUARIO_FK" FOREIGN KEY ("id_usuario")
	  REFERENCES "SCHE$SISAG"."SEG_USUARIO" ("id_usuario") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEG_SESION
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_SESION" ADD CONSTRAINT "SESION_USUARIO_FK" FOREIGN KEY ("id_usuario")
	  REFERENCES "SCHE$SISAG"."SEG_USUARIO" ("id_usuario") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEG_USUARIO
--------------------------------------------------------

  ALTER TABLE "SCHE$SISAG"."SEG_USUARIO" ADD CONSTRAINT "SEG_USUARIO_FK1" FOREIGN KEY ("id_persona")
	  REFERENCES "SCHE$SISAG"."RRHH_PERSONA" ("id_persona") ENABLE;
